### ISSUE TITLE
Clarification on Drow Legacy feat

### ISSUE THREAD

**Issue by Drejzer** [JoshuaD84/new-bard-handbook#3]
I don't think Half-elves loose anything when they take the feat, since nowhere in the feat description it is stated that the benefits of the feat replace any standard half elf racial features.

Moreover the **Normal** entry even states "A half-elf with drow ancestry normally just receives the half-elf racial traits as described in the Player’s Handbook." Which (to me at least) implies that the **Benefit** and **Special** entries apply on top of what Half-Elves already get by default.

**Comment by JoshuaD84** [comment]
Updated, thanks!
